#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Abyss.Items;
using Abyss.Shop;
using Abyssbound.Loot;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class Zone1FarmReadySetupEditor
{
    private const string LootRoot = "Assets/Resources/Loot";
    private const string LootItemsRoot = "Assets/Resources/Loot/Items";
    private const string LootTablesRoot = "Assets/Resources/Loot/Tables";
    private const string LootItemRegistryPath = "Assets/Resources/Loot/ItemRegistry.asset";

    private const string AutoGenLootItemsFolder = "Assets/Resources/Loot/Items/Tier1/AutoGenerated";

    private const string Zone1TrashTablePath = "Assets/Resources/Loot/Tables/Zone1_Trash.asset";
    private const string Zone1EliteTablePath = "Assets/Resources/Loot/Tables/Zone1_Elite.asset";
    private const string Zone1BossTablePath = "Assets/Resources/Loot/Tables/Zone1_Boss.asset";

    private const string LegacyAlchemyFolder = "Assets/GameData/Items/Alchemy";

    private const string ShopInventoriesFolder = "Assets/Abyss/Shops/Inventories";
    private const string AlchemyShopInventoryPath = "Assets/Abyss/Shops/Inventories/ShopInventory_Alchemy.asset";
    private const string WeaponsShopInventoryPath = "Assets/Abyss/Shops/Inventories/ShopInventory_Weapons.asset";
    private const string SkillingShopInventoryPath = "Assets/Abyss/Shops/Inventories/ShopInventory_Skilling.asset";

    private const string LegacyShopItemDefsFolder = "Assets/Abyss/Items/Definitions";

    private static readonly EquipmentSlot[] CoverageSlots =
    {
        EquipmentSlot.Helm,
        EquipmentSlot.Chest,
        EquipmentSlot.Legs,
        EquipmentSlot.Gloves,
        EquipmentSlot.Boots,
        EquipmentSlot.Belt,
        EquipmentSlot.Cape,
        EquipmentSlot.Ammo,
        EquipmentSlot.Amulet,
        EquipmentSlot.Artifact,
        EquipmentSlot.LeftHand,
        EquipmentSlot.RightHand,
        EquipmentSlot.Ring1,
        EquipmentSlot.Ring2,
    };

    [MenuItem("Tools/Abyssbound/Content/Report Loot V2 Equipment Coverage")]
    public static void ReportLootV2EquipmentCoverage()
    {
        if (!CanRunInEditor()) return;

        var items = LoadAllLootV2ItemsUnderResources();
        var bySlot = BuildSlotCounts(items);

        var missing = GetMissingSlots(bySlot);

        Debug.Log("[LootV2 Coverage] Scanned=" + items.Count + " under " + LootItemsRoot);
        foreach (var slot in CoverageSlots)
        {
            int count = bySlot.TryGetValue(slot, out var c) ? c : 0;
            Debug.Log($"[LootV2 Coverage] {slot}: {count}");
        }

        bool ringOk = (bySlot.TryGetValue(EquipmentSlot.Ring1, out var r1) && r1 > 0) || (bySlot.TryGetValue(EquipmentSlot.Ring2, out var r2) && r2 > 0);
        Debug.Log($"[LootV2 Coverage] Ring group ok (Ring1 or Ring2 present): {ringOk}");

        if (missing.Count == 0)
        {
            Debug.Log("[LootV2 Coverage] MissingSlots=0");
            return;
        }

        Debug.LogWarning("[LootV2 Coverage] Missing slots: " + string.Join(", ", missing));
    }

    [MenuItem("Tools/Abyssbound/Content/Generate Missing T1 Loot V2 Items")]
    public static void GenerateMissingT1LootV2Items()
    {
        if (!CanRunInEditor()) return;

        EnsureFolder("Assets/Resources");
        EnsureFolder(LootRoot);
        EnsureFolder(LootItemsRoot);
        EnsureFolder("Assets/Resources/Loot/Items/Tier1");
        EnsureFolder(AutoGenLootItemsFolder);

        var items = LoadAllLootV2ItemsUnderResources();
        var bySlot = BuildSlotCounts(items);
        var missing = GetMissingSlots(bySlot);

        int created = 0;
        foreach (var slot in missing)
        {
            if (slot == EquipmentSlot.None) continue;

            var spec = GetAutoGenSpec(slot);
            if (spec == null)
            {
                Debug.LogWarning($"[LootV2 AutoGen] No generation spec for slot={slot}");
                continue;
            }

            string assetPath = AutoGenLootItemsFolder + "/" + spec.assetFileName;
            var existing = AssetDatabase.LoadAssetAtPath<ItemDefinitionSO>(assetPath);
            if (existing != null)
            {
                Debug.Log($"[LootV2 AutoGen] Exists (skip): {assetPath}");
                continue;
            }

            // Never overwrite existing authored assets by id either.
            if (FindLootV2ItemById(spec.id) != null)
            {
                Debug.Log($"[LootV2 AutoGen] Item id already exists (skip): {spec.id}");
                continue;
            }

            var item = ScriptableObject.CreateInstance<ItemDefinitionSO>();
            ConfigureLootV2Item(item, spec);

            AssetDatabase.CreateAsset(item, assetPath);
            EditorUtility.SetDirty(item);
            created++;

            Debug.Log($"[LootV2 AutoGen] Created {spec.displayName} ({spec.id}) at {assetPath}");
        }

        EnsureItemRegistryContainsAllLootV2Items();

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        MarkActiveSceneDirty();

        Debug.Log($"[LootV2 AutoGen] Completed. Created={created}");

        // Re-run coverage report for convenience.
        ReportLootV2EquipmentCoverage();
    }

    [MenuItem("Tools/Abyssbound/Loot/Rebuild Zone1 Loot V2 Tables (Trash/Elite/Boss)")]
    public static void RebuildZone1LootV2Tables()
    {
        if (!CanRunInEditor()) return;

        var all = LoadAllLootV2ItemsUnderResources();
        var allEquip = all
            .Where(i => i != null)
            .Where(i => i.slot != EquipmentSlot.None)
            .Where(i => !IsExcludedLootV2Item(i))
            .Distinct()
            .ToList();

        var coreGearSlots = new HashSet<EquipmentSlot>
        {
            EquipmentSlot.Helm,
            EquipmentSlot.Chest,
            EquipmentSlot.Legs,
            EquipmentSlot.Gloves,
            EquipmentSlot.Boots,
            EquipmentSlot.Belt,
            EquipmentSlot.LeftHand,
            EquipmentSlot.RightHand,
        };

        var accessorySlots = new HashSet<EquipmentSlot>
        {
            EquipmentSlot.Cape,
            EquipmentSlot.Ammo,
            EquipmentSlot.Amulet,
            EquipmentSlot.Ring1,
            EquipmentSlot.Ring2,
            EquipmentSlot.Artifact,
        };

        var core = allEquip
            .Where(i => coreGearSlots.Contains(i.slot))
            .OrderBy(i => i.id ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var accessories = allEquip
            .Where(i => accessorySlots.Contains(i.slot))
            .OrderBy(i => i.id ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Deterministic inclusion rules (no randomness):
        // - Trash: core + ~25% accessories (include every 4th accessory)
        // - Elite: core + ~60% accessories (include when index%5 < 3)
        // - Boss: core + 100% accessories
        var trashAccessories = new List<ItemDefinitionSO>();
        for (int i = 0; i < accessories.Count; i++)
        {
            if ((i % 4) == 0)
                trashAccessories.Add(accessories[i]);
        }

        var eliteAccessories = new List<ItemDefinitionSO>();
        for (int i = 0; i < accessories.Count; i++)
        {
            if ((i % 5) < 3)
                eliteAccessories.Add(accessories[i]);
        }

        var trashList = core.Concat(trashAccessories).Distinct().ToList();
        var eliteList = core.Concat(eliteAccessories).Distinct().ToList();
        var bossList = core.Concat(accessories).Distinct().ToList();

        var trash = AssetDatabase.LoadAssetAtPath<LootTableSO>(Zone1TrashTablePath);
        var elite = AssetDatabase.LoadAssetAtPath<LootTableSO>(Zone1EliteTablePath);
        var boss = AssetDatabase.LoadAssetAtPath<LootTableSO>(Zone1BossTablePath);

        if (trash == null || elite == null || boss == null)
        {
            Debug.LogWarning(
                "[Zone1 Tables] Missing one or more Zone1 table assets. Expected:\n" +
                $"- {Zone1TrashTablePath}\n" +
                $"- {Zone1EliteTablePath}\n" +
                $"- {Zone1BossTablePath}");
            return;
        }

        int t = ReplaceTableItems(trash, trashList);
        int e = ReplaceTableItems(elite, eliteList);
        int b = ReplaceTableItems(boss, bossList);

        EnsureItemRegistryContainsAllLootV2Items();

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        MarkActiveSceneDirty();

        Debug.Log(
            "[Zone1 Tables] Updated (table-specific inclusion; weights=1; rarity weights unchanged).\n" +
            $"Core={core.Count} AccessoriesTotal={accessories.Count}\n" +
            $"Trash: AccessoriesIncluded={trashAccessories.Count} Items={t}\n" +
            $"Elite: AccessoriesIncluded={eliteAccessories.Count} Items={e}\n" +
            $"Boss: AccessoriesIncluded={accessories.Count} Items={b}");
    }

    [MenuItem("Tools/Abyssbound/Shops/Create + Rebuild Alchemy ShopInventory (T1)")]
    public static void CreateAndRebuildAlchemyShopInventory()
    {
        if (!CanRunInEditor()) return;

        EnsureFolder("Assets/GameData");
        EnsureFolder("Assets/GameData/Items");
        EnsureFolder(LegacyAlchemyFolder);

        EnsureFolder("Assets/Abyss");
        EnsureFolder("Assets/Abyss/Shops");
        EnsureFolder(ShopInventoriesFolder);

        var mats = EnsureLegacyAlchemyMaterials();
        if (mats.Count == 0)
        {
            Debug.LogWarning("[Alchemy] No material ItemDefinition assets were created or found; shop rebuild skipped.");
            return;
        }

        var inv = AssetDatabase.LoadAssetAtPath<ShopInventory>(AlchemyShopInventoryPath);
        bool created = false;
        if (inv == null)
        {
            inv = ScriptableObject.CreateInstance<ShopInventory>();
            AssetDatabase.CreateAsset(inv, AlchemyShopInventoryPath);
            created = true;
        }

        inv.entries ??= new List<ShopInventory.Entry>();

        // Preserve existing prices when possible.
        var existingPriceById = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in inv.entries)
        {
            if (entry == null || entry.item == null) continue;
            string id = entry.item.itemId;
            if (string.IsNullOrWhiteSpace(id)) continue;
            if (!existingPriceById.ContainsKey(id))
                existingPriceById[id] = entry.price;
        }

        inv.entries.Clear();

        foreach (var def in mats)
        {
            if (def == null) continue;
            var id = def.itemId ?? string.Empty;

            int price;
            if (existingPriceById.TryGetValue(id, out var preserved) && preserved > 0)
                price = preserved;
            else
                price = DefaultAlchemyPrice(id);

            inv.entries.Add(new ShopInventory.Entry { item = def, price = price });
        }

        EditorUtility.SetDirty(inv);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        MarkActiveSceneDirty();

        Debug.Log(created
            ? $"[Alchemy] Created {AlchemyShopInventoryPath} entries={inv.entries.Count}"
            : $"[Alchemy] Updated {AlchemyShopInventoryPath} entries={inv.entries.Count}");
    }

    [MenuItem("Tools/Abyssbound/Shops/Rebuild T1 Weapons & Gear ShopInventory")]
    public static void RebuildT1WeaponsAndGearShopInventory()
    {
        if (!CanRunInEditor()) return;

        EnsureFolder("Assets/Abyss");
        EnsureFolder("Assets/Abyss/Items");
        EnsureFolder(LegacyShopItemDefsFolder);
        EnsureFolder("Assets/Abyss/Shops");
        EnsureFolder(ShopInventoriesFolder);

        // Ensure the canonical T1 shop items exist (these IDs are already used by CreateDefaultShopAssetsEditor).
        var bronzeSword = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_BronzeSword.asset",
            id: "weapon_bronze_sword",
            displayName: "Bronze Sword",
            description: "A basic starter sword.",
            type: Abyss.Items.ItemType.Weapon,
            baseValue: 80,
            equipSlot: EquipmentSlot.RightHand,
            handedness: WeaponHandedness.OneHanded);

        var trainingBow = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_TrainingBow.asset",
            id: "weapon_training_bow",
            displayName: "Training Bow",
            description: "A basic starter bow.",
            type: Abyss.Items.ItemType.Weapon,
            baseValue: 90,
            equipSlot: EquipmentSlot.RightHand,
            handedness: WeaponHandedness.TwoHanded);

        var apprenticeStaff = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_ApprenticeStaff.asset",
            id: "weapon_apprentice_staff",
            displayName: "Apprentice Staff",
            description: "A basic starter staff.",
            type: Abyss.Items.ItemType.Weapon,
            baseValue: 100,
            equipSlot: EquipmentSlot.RightHand,
            handedness: WeaponHandedness.TwoHanded);

        var basicHelm = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_BasicHelm.asset",
            id: "armor_basic_helm",
            displayName: "Basic Helm",
            description: "Simple starter head protection.",
            type: Abyss.Items.ItemType.Misc,
            baseValue: 35,
            equipSlot: EquipmentSlot.Helm,
            handedness: WeaponHandedness.None);

        var basicChest = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_BasicChest.asset",
            id: "armor_basic_chest",
            displayName: "Basic Chest",
            description: "Simple starter body protection.",
            type: Abyss.Items.ItemType.Misc,
            baseValue: 60,
            equipSlot: EquipmentSlot.Chest,
            handedness: WeaponHandedness.None);

        var basicLegs = EnsureLegacyItem(
            LegacyShopItemDefsFolder + "/Item_BasicLegs.asset",
            id: "armor_basic_legs",
            displayName: "Basic Legs",
            description: "Simple starter leg protection.",
            type: Abyss.Items.ItemType.Misc,
            baseValue: 50,
            equipSlot: EquipmentSlot.Legs,
            handedness: WeaponHandedness.None);

        var inv = AssetDatabase.LoadAssetAtPath<ShopInventory>(WeaponsShopInventoryPath);
        bool created = false;
        if (inv == null)
        {
            inv = ScriptableObject.CreateInstance<ShopInventory>();
            AssetDatabase.CreateAsset(inv, WeaponsShopInventoryPath);
            created = true;
        }

        inv.entries ??= new List<ShopInventory.Entry>();

        // Preserve existing prices when possible.
        var existingPriceById = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in inv.entries)
        {
            if (entry == null || entry.item == null) continue;
            string id = entry.item.itemId;
            if (string.IsNullOrWhiteSpace(id)) continue;
            if (!existingPriceById.ContainsKey(id))
                existingPriceById[id] = entry.price;
        }

        var desired = new List<(ItemDefinition item, int defaultPrice)>
        {
            (bronzeSword, 80),
            (trainingBow, 95),
            (apprenticeStaff, 110),
            (basicHelm, 35),
            (basicChest, 60),
            (basicLegs, 50),
        };

        inv.entries.Clear();

        foreach (var (item, defaultPrice) in desired)
        {
            if (item == null) continue;
            var id = item.itemId ?? string.Empty;

            int price = (existingPriceById.TryGetValue(id, out var preserved) && preserved > 0)
                ? preserved
                : defaultPrice;

            inv.entries.Add(new ShopInventory.Entry { item = item, price = price });
        }

        EditorUtility.SetDirty(inv);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        MarkActiveSceneDirty();

        Debug.Log(created
            ? $"[WeaponsShop] Created {WeaponsShopInventoryPath} entries={inv.entries.Count}"
            : $"[WeaponsShop] Updated {WeaponsShopInventoryPath} entries={inv.entries.Count}");
    }

    [MenuItem("Tools/Abyssbound/Content/One-Click Zone1 Content Setup")]
    public static void OneClickZone1ContentSetup()
    {
        if (!CanRunInEditor()) return;

        Debug.Log("[Zone1 One-Click] Starting Zone1 content setup...");

        ReportLootV2EquipmentCoverage();
        GenerateMissingT1LootV2Items();
        RebuildZone1LootV2Tables();

        CreateAndRebuildAlchemyShopInventory();
        AddAlchemyMatsToSkillingShopInventory();
        RebuildT1WeaponsAndGearShopInventory();

        Debug.Log(
            "[Zone1 One-Click] Completed.\n" +
            "QA Steps:\n" +
            "1) Run Tools/Abyssbound/Content/One-Click Zone1 Content Setup\n" +
            "2) Enter Play Mode, select an enemy, then run Tools/Abyssbound/Loot/Simulate 200 Drops (Selected Enemy, Loot V2)\n" +
            "3) Verify: Report Loot V2 Equipment Coverage shows 0 missing slots\n" +
            "4) Open Weapons merchant: only T1 stock\n" +
            "5) Open Alchemy merchant: herbs + secondaries appear and STACK in inventory\n" +
            "6) Open Skilling merchant: herbs + secondaries appear\n" +
            "(Optional) Copy report: Tools/Abyssbound/Loot/Copy Last Loot V2 Sim Report");
    }

    [MenuItem("Tools/Abyssbound/Shops/Add Herbs + Secondaries To Skilling ShopInventory (T1)")]
    public static void AddAlchemyMatsToSkillingShopInventory()
    {
        if (!CanRunInEditor()) return;

        EnsureFolder("Assets/Abyss");
        EnsureFolder("Assets/Abyss/Shops");
        EnsureFolder(ShopInventoriesFolder);

        // Ensure the items exist first.
        EnsureFolder("Assets/GameData");
        EnsureFolder("Assets/GameData/Items");
        EnsureFolder(LegacyAlchemyFolder);
        var mats = EnsureLegacyAlchemyMaterials();

        var inv = AssetDatabase.LoadAssetAtPath<ShopInventory>(SkillingShopInventoryPath);
        if (inv == null)
        {
            Debug.LogWarning($"[SkillingShop] Missing ShopInventory at {SkillingShopInventoryPath}." +
                             " Skipping alchemy-mat injection.");
            return;
        }

        inv.entries ??= new List<ShopInventory.Entry>();

        var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in inv.entries)
        {
            if (entry == null || entry.item == null) continue;
            var id = entry.item.itemId;
            if (string.IsNullOrWhiteSpace(id)) continue;
            existing.Add(id);
        }

        // Requirements: ensure these itemIds are present.
        string[] requiredIds =
        {
            // Herbs
            "herb_guam",
            "herb_marrentill",
            "herb_taradromin",
            "herb_harralander",
            "herb_irit",
            "herb_avantoe",

            // Secondaries
            "sec_vial",
            "sec_ashes",
            "sec_mort_myre_fungus",
            "sec_spider_eggs",
            "sec_red_spiders_nest",
            "sec_unicorn_horn",
        };

        // Map from id to ItemDefinition (prefer the known alchemy folder creations).
        var byId = new Dictionary<string, ItemDefinition>(StringComparer.OrdinalIgnoreCase);
        foreach (var def in mats)
        {
            if (def == null || string.IsNullOrWhiteSpace(def.itemId)) continue;
            if (!byId.ContainsKey(def.itemId))
                byId[def.itemId] = def;
        }

        int added = 0;
        for (int i = 0; i < requiredIds.Length; i++)
        {
            var id = requiredIds[i];
            if (existing.Contains(id))
                continue;

            if (!byId.TryGetValue(id, out var def) || def == null)
                def = FindLegacyItemById(id);

            if (def == null)
            {
                Debug.LogWarning($"[SkillingShop] Missing ItemDefinition for required id='{id}'. Entry not added.");
                continue;
            }

            inv.entries.Add(new ShopInventory.Entry
            {
                item = def,
                price = DefaultAlchemyPrice(id)
            });
            existing.Add(id);
            added++;
        }

        if (added > 0)
        {
            EditorUtility.SetDirty(inv);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            MarkActiveSceneDirty();
        }

        Debug.Log($"[SkillingShop] Added={added} FinalCount={inv.entries.Count} Path={SkillingShopInventoryPath}");
    }

    // ----------------------
    // Loot V2 helpers
    // ----------------------

    private static List<ItemDefinitionSO> LoadAllLootV2ItemsUnderResources()
    {
        var items = new List<ItemDefinitionSO>(64);
        try
        {
            var guids = AssetDatabase.FindAssets("t:ItemDefinitionSO", new[] { LootItemsRoot });
            if (guids == null) return items;

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var item = AssetDatabase.LoadAssetAtPath<ItemDefinitionSO>(path);
                if (item != null)
                    items.Add(item);
            }
        }
        catch { }

        return items;
    }

    private static ItemDefinitionSO FindLootV2ItemById(string id)
    {
        if (string.IsNullOrWhiteSpace(id)) return null;

        try
        {
            var guids = AssetDatabase.FindAssets("t:ItemDefinitionSO", new[] { LootItemsRoot });
            if (guids == null || guids.Length == 0) return null;

            for (int i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                var item = AssetDatabase.LoadAssetAtPath<ItemDefinitionSO>(path);
                if (item == null) continue;
                if (!string.IsNullOrWhiteSpace(item.id) && string.Equals(item.id, id, StringComparison.OrdinalIgnoreCase))
                    return item;
            }
        }
        catch { }

        return null;
    }

    private static Dictionary<EquipmentSlot, int> BuildSlotCounts(List<ItemDefinitionSO> items)
    {
        var map = new Dictionary<EquipmentSlot, int>();
        foreach (var item in items)
        {
            if (item == null) continue;
            var slot = item.slot;
            if (slot == EquipmentSlot.None) continue;

            map[slot] = map.TryGetValue(slot, out var c) ? (c + 1) : 1;
        }
        return map;
    }

    private static List<EquipmentSlot> GetMissingSlots(Dictionary<EquipmentSlot, int> bySlot)
    {
        var missing = new List<EquipmentSlot>();

        foreach (var slot in CoverageSlots)
        {
            if (slot == EquipmentSlot.Ring1 || slot == EquipmentSlot.Ring2)
                continue; // handle ring group separately

            bool ok = bySlot.TryGetValue(slot, out var c) && c > 0;
            if (!ok)
                missing.Add(slot);
        }

        // Ring group: ok if either ring slot is present.
        bool ringOk = (bySlot.TryGetValue(EquipmentSlot.Ring1, out var r1) && r1 > 0) || (bySlot.TryGetValue(EquipmentSlot.Ring2, out var r2) && r2 > 0);
        if (!ringOk)
            missing.Add(EquipmentSlot.Ring1);

        return missing;
    }

    private sealed class LootV2AutoGenSpec
    {
        public string assetFileName;
        public string id;
        public string displayName;
        public EquipmentSlot slot;
        public List<StatMod> baseStats;
        public List<AffixTag> tags;
        public string silhouetteIconName;
    }

    private static LootV2AutoGenSpec GetAutoGenSpec(EquipmentSlot slot)
    {
        // Use the same silhouette sprite names as BuildPlayerEquipmentUIEditor.
        switch (slot)
        {
            case EquipmentSlot.Helm:
                return MakeArmor(slot, "T1_Helm_Basic.asset", "t1_helm_basic", "T1 Helm (Basic)", "sil_helm", defense: 1f);
            case EquipmentSlot.Chest:
                return MakeArmor(slot, "T1_Chest_Basic.asset", "t1_chest_basic", "T1 Chest (Basic)", "sil_chest", defense: 1f);
            case EquipmentSlot.Legs:
                return MakeArmor(slot, "T1_Legs_Basic.asset", "t1_legs_basic", "T1 Legs (Basic)", ChooseSilhouetteIconName("sil_legs", "sil_pants", "sil_chest", "sil_belt"), defense: 1f);
            case EquipmentSlot.Gloves:
                return MakeArmor(slot, "T1_Gloves_Basic.asset", "t1_gloves_basic", "T1 Gloves (Basic)", "sil_gloves", defense: 1f);
            case EquipmentSlot.Boots:
                return MakeArmor(slot, "T1_Boots_Basic.asset", "t1_boots_basic", "T1 Boots (Basic)", "sil_boots", defense: 1f);
            case EquipmentSlot.Belt:
                return MakeArmor(slot, "T1_Belt_Basic.asset", "t1_belt_basic", "T1 Belt (Basic)", "sil_belt", defense: 1f);
            case EquipmentSlot.Cape:
                return MakeArmor(slot, "T1_Cape_Basic.asset", "t1_cape_basic", "T1 Cape (Basic)", "sil_cape", maxHealth: 2f);
            case EquipmentSlot.Ammo:
                return MakeArmor(slot, "T1_Ammo_Basic.asset", "t1_ammo_basic", "T1 Ammo (Basic)", "sil_arrows", maxHealth: 2f);

            case EquipmentSlot.Amulet: // also covers Necklace alias
                return MakeJewelry(slot, "T1_Necklace_Basic.asset", "t1_necklace_basic", "T1 Necklace (Basic)", "sil_amulet", maxHealth: 2f);

            case EquipmentSlot.Artifact:
                return MakeJewelry(slot, "T1_Artifact_Basic.asset", "t1_artifact_basic", "T1 Artifact (Basic)", "sil_orb", maxHealth: 2f);

            case EquipmentSlot.Ring1:
                return MakeJewelry(slot, "T1_Ring_Basic.asset", "t1_ring_basic", "T1 Ring (Basic)", "sil_ring", maxHealth: 2f);

            case EquipmentSlot.LeftHand:
                return new LootV2AutoGenSpec
                {
                    assetFileName = "T1_LeftHand_Shield.asset",
                    id = "t1_lefthand_shield",
                    displayName = "T1 LeftHand (Shield)",
                    slot = EquipmentSlot.LeftHand,
                    baseStats = new List<StatMod> { new StatMod { stat = StatType.Defense, value = 1f, percent = false } },
                    tags = new List<AffixTag> { AffixTag.Armor },
                    silhouetteIconName = "sil_shield",
                };

            case EquipmentSlot.RightHand:
                return new LootV2AutoGenSpec
                {
                    assetFileName = "T1_RightHand_Dagger.asset",
                    id = "t1_righthand_dagger",
                    displayName = "T1 RightHand (Dagger)",
                    slot = EquipmentSlot.RightHand,
                    baseStats = new List<StatMod> { new StatMod { stat = StatType.MeleeDamage, value = 1f, percent = false } },
                    tags = new List<AffixTag> { AffixTag.WeaponMelee },
                    silhouetteIconName = "sil_sword",
                };

            default:
                return null;
        }
    }

    private static LootV2AutoGenSpec MakeArmor(EquipmentSlot slot, string fileName, string id, string displayName, string iconName, float defense = 0f, float maxHealth = 0f)
    {
        var stats = new List<StatMod>(2);
        if (defense != 0f) stats.Add(new StatMod { stat = StatType.Defense, value = defense, percent = false });
        if (maxHealth != 0f) stats.Add(new StatMod { stat = StatType.MaxHealth, value = maxHealth, percent = false });

        return new LootV2AutoGenSpec
        {
            assetFileName = fileName,
            id = id,
            displayName = displayName,
            slot = slot,
            baseStats = stats,
            tags = new List<AffixTag> { AffixTag.Armor },
            silhouetteIconName = iconName,
        };
    }

    private static LootV2AutoGenSpec MakeJewelry(EquipmentSlot slot, string fileName, string id, string displayName, string iconName, float maxHealth = 0f, float defense = 0f)
    {
        var stats = new List<StatMod>(2);
        if (maxHealth != 0f) stats.Add(new StatMod { stat = StatType.MaxHealth, value = maxHealth, percent = false });
        if (defense != 0f) stats.Add(new StatMod { stat = StatType.Defense, value = defense, percent = false });

        return new LootV2AutoGenSpec
        {
            assetFileName = fileName,
            id = id,
            displayName = displayName,
            slot = slot,
            baseStats = stats,
            tags = new List<AffixTag> { AffixTag.Jewelry },
            silhouetteIconName = iconName,
        };
    }

    private static void ConfigureLootV2Item(ItemDefinitionSO item, LootV2AutoGenSpec spec)
    {
        if (item == null || spec == null) return;

        item.id = spec.id;
        item.displayName = spec.displayName;
        item.slot = spec.slot;
        item.occupiesSlots = new List<EquipmentSlot>();

        item.baseStats = spec.baseStats ?? new List<StatMod>();
        item.allowedAffixTags = spec.tags ?? new List<AffixTag>();

        item.set = null;
        item.setId = string.Empty;

        item.icon = TryLoadSilhouetteSprite(spec.silhouetteIconName);

        EditorUtility.SetDirty(item);
    }

    private static Sprite TryLoadSilhouetteSprite(string iconName)
    {
        if (string.IsNullOrWhiteSpace(iconName)) return null;

        const string folder = "Assets/Abyss/Equipment/Icons/";
        var path = folder + iconName + ".png";

        var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
        if (sprite == null)
            Debug.LogWarning($"[LootV2 AutoGen] Missing fallback icon sprite at {path}");

        return sprite;
    }

    private static string ChooseSilhouetteIconName(params string[] iconNames)
    {
        if (iconNames == null || iconNames.Length == 0)
            return string.Empty;

        const string folder = "Assets/Abyss/Equipment/Icons/";
        for (int i = 0; i < iconNames.Length; i++)
        {
            var name = iconNames[i];
            if (string.IsNullOrWhiteSpace(name))
                continue;

            var path = folder + name + ".png";
            if (AssetDatabase.LoadAssetAtPath<Sprite>(path) != null)
                return name;
        }

        Debug.LogWarning("[LootV2 AutoGen] No matching silhouette icon found for candidates: " + string.Join(", ", iconNames));
        return iconNames[0] ?? string.Empty;
    }

    private static bool IsExcludedLootV2Item(ItemDefinitionSO item)
    {
        if (item == null) return true;

        string assetName = item.name ?? string.Empty;
        string id = item.id ?? string.Empty;

        return StartsWithAny(assetName, "Test_", "Debug_", "QA_") || StartsWithAny(id, "Test_", "Debug_", "QA_");
    }

    private static bool StartsWithAny(string s, params string[] prefixes)
    {
        if (string.IsNullOrEmpty(s) || prefixes == null) return false;

        for (int i = 0; i < prefixes.Length; i++)
        {
            var p = prefixes[i];
            if (string.IsNullOrEmpty(p)) continue;
            if (s.StartsWith(p, StringComparison.OrdinalIgnoreCase)) return true;
        }

        return false;
    }

    private static int ReplaceTableItems(LootTableSO table, List<ItemDefinitionSO> items)
    {
        if (table == null) return 0;

        table.items = new List<LootTableSO.WeightedItemEntry>(items != null ? items.Count : 0);

        if (items != null)
        {
            for (int i = 0; i < items.Count; i++)
            {
                var it = items[i];
                if (it == null) continue;
                table.items.Add(new LootTableSO.WeightedItemEntry { item = it, weight = 1f });
            }
        }

        EditorUtility.SetDirty(table);
        return table.items.Count;
    }

    private static void EnsureItemRegistryContainsAllLootV2Items()
    {
        var reg = AssetDatabase.LoadAssetAtPath<ItemRegistrySO>(LootItemRegistryPath);
        if (reg == null)
        {
            Debug.LogWarning($"[LootV2 Registry] Missing ItemRegistry at {LootItemRegistryPath}. Run Tools/Abyssbound/Content/Create Starter Loot Content.");
            return;
        }

        reg.items ??= new List<ItemDefinitionSO>();

        var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var it in reg.items)
        {
            if (it == null || string.IsNullOrWhiteSpace(it.id)) continue;
            existing.Add(it.id);
        }

        var all = LoadAllLootV2ItemsUnderResources();
        int added = 0;

        foreach (var it in all)
        {
            if (it == null || string.IsNullOrWhiteSpace(it.id)) continue;
            if (existing.Contains(it.id)) continue;

            reg.items.Add(it);
            existing.Add(it.id);
            added++;
        }

        if (added > 0)
        {
            EditorUtility.SetDirty(reg);
            Debug.Log($"[LootV2 Registry] Added {added} ItemDefinitionSO refs to {LootItemRegistryPath}");
        }
    }

    // ----------------------
    // Legacy alchemy helpers
    // ----------------------

    private static List<ItemDefinition> EnsureLegacyAlchemyMaterials()
    {
        var specs = new List<(string id, string name)>
        {
            ("herb_guam", "Guam"),
            ("herb_marrentill", "Marrentill"),
            ("herb_taradromin", "Taradromin"),
            ("herb_harralander", "Harralander"),
            ("herb_irit", "Irit"),
            ("herb_avantoe", "Avantoe"),

            ("sec_vial", "Vial"),
            ("sec_ashes", "Ashes"),
            ("sec_mort_myre_fungus", "Mort Myre Fungus"),
            ("sec_spider_eggs", "Spider Eggs"),
            ("sec_red_spiders_nest", "Red Spiders' Nest"),
            ("sec_unicorn_horn", "Unicorn Horn"),
        };

        var result = new List<ItemDefinition>(specs.Count);

        foreach (var (id, name) in specs)
        {
            var assetPath = LegacyAlchemyFolder + "/Item_" + id + ".asset";

            var def = FindLegacyItemById(id);
            if (def == null)
                def = AssetDatabase.LoadAssetAtPath<ItemDefinition>(assetPath);

            bool created = false;
            if (def == null)
            {
                def = ScriptableObject.CreateInstance<ItemDefinition>();
                AssetDatabase.CreateAsset(def, assetPath);
                created = true;
            }

            ApplyLegacyAlchemyDefaults(def, id, name);

            if (created)
                Debug.Log($"[Alchemy] Created ItemDefinition {id} at {assetPath}");

            if (def != null)
                result.Add(def);
        }

        // Keep a stable order for shop listing.
        result = result
            .Where(d => d != null)
            .OrderBy(d => d.itemId, StringComparer.OrdinalIgnoreCase)
            .ToList();

        return result;
    }

    private static void ApplyLegacyAlchemyDefaults(ItemDefinition def, string id, string displayName)
    {
        if (def == null) return;

        if (!string.IsNullOrWhiteSpace(id) && !string.Equals(def.itemId, id, StringComparison.OrdinalIgnoreCase))
            def.itemId = id;

        if (string.IsNullOrWhiteSpace(def.displayName))
            def.displayName = displayName;

        // Make them stackable by key (non-equippable).
        if (def.equipmentSlot != EquipmentSlot.None)
            def.equipmentSlot = EquipmentSlot.None;

        if (def.weaponHandedness != WeaponHandedness.None)
            def.weaponHandedness = WeaponHandedness.None;

        if (def.itemType == Abyss.Items.ItemType.None)
            def.itemType = Abyss.Items.ItemType.Skilling;

        if (def.baseValue <= 0)
            def.baseValue = 1;

        // Optional generic icon (ok if missing).
        if (def.icon == null)
            def.icon = TryLoadAnyMaterialSprite();

        EditorUtility.SetDirty(def);
    }

    private static Sprite TryLoadAnyMaterialSprite()
    {
        // Best-effort: pick any existing sprite that looks like a material.
        string[] candidates = { "mat_", "icon_mat", "icon_material", "material" };

        for (int i = 0; i < candidates.Length; i++)
        {
            try
            {
                var guids = AssetDatabase.FindAssets(candidates[i] + " t:Sprite");
                if (guids != null && guids.Length > 0)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guids[0]);
                    var s = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                    if (s != null) return s;
                }
            }
            catch { }
        }

        return null;
    }

    private static int DefaultAlchemyPrice(string itemId)
    {
        if (string.IsNullOrWhiteSpace(itemId)) return 1;

        if (itemId.Equals("sec_vial", StringComparison.OrdinalIgnoreCase))
            return 1;

        if (itemId.StartsWith("herb_", StringComparison.OrdinalIgnoreCase))
            return 5;

        if (itemId.StartsWith("sec_", StringComparison.OrdinalIgnoreCase))
            return 10;

        return 5;
    }

    // ----------------------
    // Legacy shop helpers
    // ----------------------

    private static ItemDefinition EnsureLegacyItem(
        string assetPath,
        string id,
        string displayName,
        string description,
        Abyss.Items.ItemType type,
        int baseValue,
        EquipmentSlot equipSlot,
        WeaponHandedness handedness)
    {
        var existingById = FindLegacyItemById(id);
        if (existingById != null)
        {
            ApplyLegacyItemDefaults(existingById, id, displayName, description, type, baseValue, equipSlot, handedness);
            return existingById;
        }

        var existingByPath = AssetDatabase.LoadAssetAtPath<ItemDefinition>(assetPath);
        if (existingByPath != null)
        {
            ApplyLegacyItemDefaults(existingByPath, id, displayName, description, type, baseValue, equipSlot, handedness);
            return existingByPath;
        }

        var def = ScriptableObject.CreateInstance<ItemDefinition>();
        ApplyLegacyItemDefaults(def, id, displayName, description, type, baseValue, equipSlot, handedness);
        AssetDatabase.CreateAsset(def, assetPath);
        EditorUtility.SetDirty(def);
        Debug.Log($"[WeaponsShop] Created ItemDefinition {displayName} ({id}) at {assetPath}");
        return def;
    }

    private static void ApplyLegacyItemDefaults(
        ItemDefinition def,
        string id,
        string displayName,
        string description,
        Abyss.Items.ItemType type,
        int baseValue,
        EquipmentSlot equipSlot,
        WeaponHandedness handedness)
    {
        if (def == null) return;

        if (!string.IsNullOrWhiteSpace(id) && !string.Equals(def.itemId, id, StringComparison.OrdinalIgnoreCase))
            def.itemId = id;

        if (string.IsNullOrWhiteSpace(def.displayName))
            def.displayName = displayName;

        if (string.IsNullOrWhiteSpace(def.description))
            def.description = description;

        if (def.itemType == Abyss.Items.ItemType.None)
            def.itemType = type;

        if (def.baseValue <= 0)
            def.baseValue = baseValue;

        if (equipSlot != EquipmentSlot.None && def.equipmentSlot == EquipmentSlot.None)
            def.equipmentSlot = equipSlot;

        if (handedness != WeaponHandedness.None && def.weaponHandedness == WeaponHandedness.None)
            def.weaponHandedness = handedness;

        if (def.rarity == 0)
            def.rarity = Abyss.Items.ItemRarity.Common;

        EditorUtility.SetDirty(def);
    }

    private static ItemDefinition FindLegacyItemById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        try
        {
            var guids = AssetDatabase.FindAssets("t:ItemDefinition");
            if (guids == null || guids.Length == 0)
                return null;

            for (int i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                if (string.IsNullOrWhiteSpace(path))
                    continue;

                var def = AssetDatabase.LoadAssetAtPath<ItemDefinition>(path);
                if (def == null)
                    continue;

                if (!string.IsNullOrWhiteSpace(def.itemId) && string.Equals(def.itemId, id, StringComparison.OrdinalIgnoreCase))
                    return def;
            }
        }
        catch { }

        return null;
    }

    // ----------------------
    // Editor utilities
    // ----------------------

    private static bool CanRunInEditor()
    {
        if (Application.isPlaying)
        {
            Debug.LogWarning("Run this in Edit Mode (not Play Mode). ");
            return false;
        }

        return true;
    }

    private static void EnsureFolder(string path)
    {
        if (AssetDatabase.IsValidFolder(path)) return;

        string parent = Path.GetDirectoryName(path)?.Replace('\\', '/');
        string folder = Path.GetFileName(path);
        if (string.IsNullOrWhiteSpace(parent) || string.IsNullOrWhiteSpace(folder)) return;

        if (!AssetDatabase.IsValidFolder(parent))
            EnsureFolder(parent);

        AssetDatabase.CreateFolder(parent, folder);
    }

    private static void MarkActiveSceneDirty()
    {
        try
        {
            if (!Application.isPlaying)
                EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        }
        catch { }
    }
}
#endif
