using System;
using UnityEngine;

namespace AiAssistant
{
    /// <summary>
    /// Represents a single tool command generated by the AI and executed in the Unity Editor.
    /// Designed for UnityEngine.JsonUtility compatibility (public fields, [Serializable]).
    /// </summary>
    [Serializable]
    public class AiCommand
    {
        // Relative transforms (for move/rotate/scale deltas)
        public Vec3 deltaPosition;
        public Vec3 deltaRotationEuler;
        public Vec3 deltaScale;

        // Helper properties for null/default checks
        public bool HasPosition => !(position.x == 0f && position.y == 0f && position.z == 0f);
        public bool HasRotation => !(rotation.x == 0f && rotation.y == 0f && rotation.z == 0f);
        public bool HasScale => !(scale.x == 0f && scale.y == 0f && scale.z == 0f);
        public bool HasDeltaPosition => !(deltaPosition.x == 0f && deltaPosition.y == 0f && deltaPosition.z == 0f);
        public bool HasDeltaRotation => !(deltaRotationEuler.x == 0f && deltaRotationEuler.y == 0f && deltaRotationEuler.z == 0f);
        public bool HasDeltaScale => !(deltaScale.x == 0f && deltaScale.y == 0f && deltaScale.z == 0f);
    
        // ---------------------------
        // Core routing
        // ---------------------------
        public string action;          // e.g. "create_primitive", "move_object", etc.
        public string description;     // optional human-readable note from AI
        // If true, executor must NOT accept fallback actions
        public bool requireExactAction = false;

        // ---------------------------
        // Object identification (backward compatible)
        // ---------------------------

        // Preferred
        public string name;

        // Legacy / alternate fields the model might emit
        public string targetName;
        public string objectName;

        // Rename support
        public string newName;

        // Parenting support
        public string parentName;
        // set_parent support
        public string childName;
        public bool worldPositionStays = true;

        // ---------------------------
        // Creation
        // ---------------------------

        // create_primitive
        public string primitiveType;   // "Cube", "Sphere", "Capsule", "Cylinder", "Plane", "Quad"

        // create_prefab / scatter_prefabs
        public string prefabName;      // preferred
        public string prefab;          // legacy alternate

        // Optional: parent for created objects
        public string parent;          // parent object name (alternate to parentName)

        // ---------------------------
        // Transforms
        // ---------------------------
        public Vec3 position;
        public Vec3 rotation;
        public Vec3 scale;

        // If you want to create empties and optionally reset transform
        public bool resetTransform = true;

        // ---------------------------
        // Placement patterns
        // ---------------------------

        // place_in_line / grid / circle / ring
        public int count = 0;

        // Line
        public Vec3 start;
        public Vec3 end;
        public float spacing = 0f;

        // Grid
        public int rows = 0;
        public int columns = 0;
        public float rowSpacing = 0f;
        public float columnSpacing = 0f;

        // Circle/Ring
        public Vec3 center;
        public float radius = 0f;
        public float innerRadius = 0f; // for ring (optional)

        // ---------------------------
        // Scatter
        // ---------------------------

        // scatter_primitives / scatter_prefabs
        public Vec3 areaCenter;
        public Vec3 areaSize;          // x,z commonly used; y can be 0
        public int amount = 0;

        // Random scale range
        public float minScale = 1f;
        public float maxScale = 1f;

        // Random rotation
        public bool randomYawOnly = true;

        // Naming pattern support like "Rock_{i}"
        public string namePattern;

        // ---------------------------
        // Helper methods
        // ---------------------------

        /// <summary>
        /// Resolve object name in a backward-compatible way.
        /// Priority:
        /// 1) name
        /// 2) targetName
        /// 3) objectName
        /// </summary>
        public string ResolveName()
        {
            if (!string.IsNullOrEmpty(name)) return name;
            if (!string.IsNullOrEmpty(targetName)) return targetName;
            if (!string.IsNullOrEmpty(objectName)) return objectName;
            return null;
        }

        /// <summary>
        /// Resolve prefab name in a backward-compatible way.
        /// Priority:
        /// 1) prefabName
        /// 2) prefab
        /// </summary>
        public string ResolvePrefabName()
        {
            if (!string.IsNullOrEmpty(prefabName)) return prefabName;
            if (!string.IsNullOrEmpty(prefab)) return prefab;
            return null;
        }

        /// <summary>
        /// Resolve parent name in a backward-compatible way.
        /// Priority:
        /// 1) parentName
        /// 2) parent
        /// </summary>
        public string ResolveParentName()
        {
            if (!string.IsNullOrEmpty(parentName)) return parentName;
            if (!string.IsNullOrEmpty(parent)) return parent;
            return null;
        }
    }

    /// <summary>
    /// JsonUtility-friendly Vector3 representation.
    /// Use cmd.position.ToVector3() etc.
    /// </summary>
    [Serializable]
    public struct Vec3
    {
        public float x;
        public float y;
        public float z;

        public Vec3(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public Vector3 ToVector3()
        {
            return new Vector3(x, y, z);
        }

        public static Vec3 FromVector3(Vector3 v)
        {
            return new Vec3(v.x, v.y, v.z);
        }
    }
}
